# Generated by Django 5.0.2 on 2024-02-09 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=40)),
                ('productprice', models.FloatField()),
                ('productdesc', models.TextField()),
                ('productimg', models.ImageField(upload_to='photos')),
            ],
        ),
    ]
