# Generated by Django 5.0.2 on 2024-04-10 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_carttable"),
    ]

    operations = [
        migrations.CreateModel(
            name="ordertable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("finaltotal", models.IntegerField()),
                ("phoneno", models.IntegerField()),
                ("address", models.TextField()),
                ("paymode", models.CharField(max_length=40)),
                ("timestamp", models.DateTimeField()),
                (
                    "userid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.registertable",
                    ),
                ),
            ],
        ),
    ]
