# Generated by Django 5.0.2 on 2024-04-12 04:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_ordertable"),
    ]

    operations = [
        migrations.AddField(
            model_name="productdetail",
            name="status",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="ordertable",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
